// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAllRecentActivitiesData, GetAllRecentActivitiesErrors, GetAllRecentActivitiesResponses, GetCountersData, GetCountersErrors, GetCountersResponses, GetPendingData, GetPendingErrors, GetPendingResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class TheDashboardResource {
    public static getAllRecentActivities<ThrowOnError extends boolean = false>(options?: Options<GetAllRecentActivitiesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAllRecentActivitiesResponses, GetAllRecentActivitiesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/api/the-dashboard/dashboard/get-all-recent-activities',
            ...options
        });
    }
    
    public static getCounters<ThrowOnError extends boolean = false>(options?: Options<GetCountersData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCountersResponses, GetCountersErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/api/the-dashboard/dashboard/get-counters',
            ...options
        });
    }
    
    public static getPending<ThrowOnError extends boolean = false>(options?: Options<GetPendingData, ThrowOnError>) {
        return (options?.client ?? client).get<GetPendingResponses, GetPendingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/api/the-dashboard/dashboard/get-pending',
            ...options
        });
    }
}
