// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:24760/' | (string & {});
};

export type CountersFrontendModel = {
    counters: Array<DashboardCounterModel>;
};

export type DashboardCounterModel = {
    localizationKey: string;
    text: string;
    count: number | string;
    clickUrl: string;
    clickElement: string;
    style: string;
};

export type PendingContentNotScheduledFrontendModel = {
    count: number | string;
    items: Array<RecentActivityFrontendModel>;
};

export type RecentActivitiesFrontendModel = {
    allItems: Array<RecentActivityFrontendModel>;
    yourItems: Array<RecentActivityFrontendModel>;
};

export type RecentActivityFrontendModel = {
    activityType: string;
    nodeName: string;
    nodeKey: string;
    user: UserFrontendModel;
    datestamp: string;
    scheduledPublishDate?: null | string;
};

export type UserAvatarFrontendModel = {
    src: string;
    srcSet: string;
};

export type UserFrontendModel = {
    name: string;
    avatar: UserAvatarFrontendModel;
};

export type GetAllRecentActivitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/api/the-dashboard/dashboard/get-all-recent-activities';
};

export type GetAllRecentActivitiesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllRecentActivitiesResponses = {
    /**
     * OK
     */
    200: RecentActivitiesFrontendModel;
};

export type GetAllRecentActivitiesResponse = GetAllRecentActivitiesResponses[keyof GetAllRecentActivitiesResponses];

export type GetCountersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/api/the-dashboard/dashboard/get-counters';
};

export type GetCountersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCountersResponses = {
    /**
     * OK
     */
    200: CountersFrontendModel;
};

export type GetCountersResponse = GetCountersResponses[keyof GetCountersResponses];

export type GetPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/api/the-dashboard/dashboard/get-pending';
};

export type GetPendingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPendingResponses = {
    /**
     * OK
     */
    200: PendingContentNotScheduledFrontendModel;
};

export type GetPendingResponse = GetPendingResponses[keyof GetPendingResponses];
